spring:
    application:
        name: computation-service
server:
    port: 8071
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-service:8070/eureka/
