spring:
    application:
        name: client-service
server:
    port: 8072
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    instance:
        hostname:  localhost

