spring:
    application:
        name: gateway-service
server:
    port: 8073
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-service:8070/eureka/
